In [1]:
import sys

sys.path.append("..")
from src.data_preprocessing import load_data, remove_unwanted_columns, convert_to_datetime

In [3]:
df = load_data("../data/raw/supermarket_inventory_data2.xlsx")
df.head()

,date,product_id,product_name,Category,Supplier,price,current_stock,StockValue,ReorderLevel,ReorderQuantity,quantity_sold,SalesValue,LastSoldDate,LastRestockDate,NextRestockDate,DeliveryTimeDays,DeliveryStatus
0,2024-03-09,a8cf4d43-f0fc-43b0-a6f6-74f30b13b5db,Juice,Beverages,Mcdowell Group,89.94,55,4946.70,34,47,4,359.76,2024-04-18,2024-06-10,2024-07-04,9,On Time
1,2024-03-12,9740c875-68c3-4909-8f88-8069bf5ab35b,Bread,Bakery,"Nunez, Miles and Palmer",9.82,189,1855.98,12,22,5,49.10,2024-06-12,2024-06-22,2024-06-29,3,On Time
2,2024-01-23,98434ac8-5c4d-42c7-a26d-48c35f4849c9,Granola Bars,Snacks,Johnson-Vincent,48.66,130,6325.80,29,24,19,924.54,2024-04-29,2024-05-19,2024-05-28,7,Delayed
3,2024-03-27,438b285c-839f-413a-9d5d-6dc8d24a7a8d,Cream,Dairy,Key-Shah,54.87,96,5267.52,27,20,65,3566.55,2024-05-31,2024-02-24,2024-02-27,3,Partial Delivery
4,2024-01-21,45dd839a-911a-4c87-8217-5052b6a2c7aa,Potato,Produce,Jones Ltd,49.69,109,5416.21,9,66,11,546.59,2024-03-01,2024-05-25,2024-06-12,10,Partial Delivery

In [4]:
df = remove_unwanted_columns(df, ["Category", "Supplier", "ReorderLevel","ReorderQuantity", "StockValue", "SalesValue", "LastSoldDate", "LastRestockDate", "NextRestockDate", "DeliveryTimeDays", "DeliveryStatus"])
df.head()

,date,product_id,product_name,price,current_stock,quantity_sold
0,2024-03-09,a8cf4d43-f0fc-43b0-a6f6-74f30b13b5db,Juice,89.94,55,4
1,2024-03-12,9740c875-68c3-4909-8f88-8069bf5ab35b,Bread,9.82,189,5
2,2024-01-23,98434ac8-5c4d-42c7-a26d-48c35f4849c9,Granola Bars,48.66,130,19
3,2024-03-27,438b285c-839f-413a-9d5d-6dc8d24a7a8d,Cream,54.87,96,65
4,2024-01-21,45dd839a-911a-4c87-8217-5052b6a2c7aa,Potato,49.69,109,11

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           10000 non-null  object
 1   product_id     10000 non-null  object
 2   product_name   10000 non-null  object
 3   price          10000 non-null  float64
 4   current_stock  10000 non-null  int64
 5   quantity_sold  10000 non-null  int64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.9+ KB

In [6]:
df = convert_to_datetime(df, "date")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           10000 non-null  datetime64[ns]
 1   product_id     10000 non-null  object
 2   product_name   10000 non-null  object
 3   price          10000 non-null  float64
 4   current_stock  10000 non-null  int64
 5   quantity_sold  10000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 468.9+ KB